### ISSUE TITLE
Does not compile in Unity 5.3

### ISSUE THREAD

**Issue by punkouter2021** [Unity3dAzure/AppServicesDemo#11]
![image](https://cloud.githubusercontent.com/assets/2973092/14439171/d33a8272-fff7-11e5-942b-31cbf98c8890.png)

**Comment by deadlyfingers** [comment]
Try switching off Unity processing plugins on Windows... 
1. In Unity project select _Plugins > Pathfinding.JsonFx.dll_
2. Check **Don't process**
<img width="217" alt="dont-process-plugin" src="https://cloud.githubusercontent.com/assets/1880480/14472178/dd1f700c-00e9-11e6-8b17-b9a537574744.PNG">
3. Then **Apply**

Maybe there is an option to preconfigure the JsonFx plugin with Unity as I would prefer not to having to make people do this?

**Comment by deadlyfingers** [comment]
@punkouter What version of Windows app are you building for? I've got it to build for Windows 10 Universal App.

**Comment by punkouter2021** [comment]
I am dumb. I needed to set 'Build Settings' to Windows and it went away.

Still not sure how to create the table though. The new Azure portal has this 'EZY TABLES' concept so trying to figure out how to create the data source the demo code wants

**Comment by deadlyfingers** [comment]
I need to create additional documentation for building for each platform that Unity supports. But building for Windows can be tricky. 'Easy Tables' is what I'm using for Azure App Service. For building Windows App I used the **x64** configuration then **Build > Build Solution**
<img width="480" alt="x64-build" src="https://cloud.githubusercontent.com/assets/1880480/14475809/e5be778c-00fb-11e6-9532-8a56045d3c0c.PNG">

PS. I have a hot fix #12 coming in for Unity Editor on Windows and Azure App Service. Once that's in I will close this issue. So you might want to wait until that's in.

**Comment by punkouter2021** [comment]
The easiest and best way I think is create a screen capture where you create the app service and set it up, load the sample scene and run the demo. That would help me a lot. From there I should know enough to start customizing.

**Comment by deadlyfingers** [comment]
@punkouter yes I'll have to get a screen recording done and add that to the readme #14. Btw that's the Windows Unity Editor fix in for Azure App Services.
