### ISSUE TITLE
Specific instructions on how to create the HighScore table with a Mobile App Service

### ISSUE THREAD

**Issue by punkouter2021** [Unity3dAzure/AppServicesDemo#17]
I created an easy table and a database.

Not sure if that is what I do or something else. Where exactly do I past in the js script? 

How would an example that uses a API App Service be different ? 

I imagine in the long run I would want to create Azure API App Service since you have swagger and can then easily expose that endpoint to other things like LOGIC APPS

**Comment by deadlyfingers** [comment]
@punkouter everything shown in the Highscore Azure Mobile Service demo will work with an Azure App Service. I will publish a detailed blog post about setting up Azure App Service as part of issue #14. But here's some pointers to go with for now - 
1. Using Azure App's 'Easy Tables' create a new 'Highscores' table - (incase case sensitive type name exactly as shown)
   ![1-easytables](https://cloud.githubusercontent.com/assets/1880480/14511687/3b835022-01d1-11e6-8bb7-c05ee2f190d6.png)
2. Set all table permissions to allow anonymous access to start with.
   ![2-tablepermissions](https://cloud.githubusercontent.com/assets/1880480/14511689/413586de-01d1-11e6-9040-1ddbf83d9de2.png)
3. Manage schema to add _Number_ column for '**score**' and _String_ column for '**userId**'
   ![3-manageschema](https://cloud.githubusercontent.com/assets/1880480/14511693/465a7b7e-01d1-11e6-9e58-f4098efa29a8.png)
4. Set CORs to '*' to allow all origins to start with 
   ![cors](https://cloud.githubusercontent.com/assets/1880480/14511704/5398cd0e-01d1-11e6-9bf5-b4143c4525e6.png)

Finally you can also replicate custom API feature of Mobile Services using Azure App Service's 'Easy APIs'. In this demo I created an API called 'hello' to return some _helloworld_ text.
![easyapis](https://cloud.githubusercontent.com/assets/1880480/14511743/8df9cc14-01d1-11e6-94eb-72f9f141d845.png)

**Comment by punkouter2021** [comment]
How are you writing the custom API ?  Do I do it all in azure?  Do I create the Mobile App starting from VS2015 and write it there? If I do it within azure then how do I get that .csproj file with the code?  OR is it meant to only be done in Azure?

**Comment by deadlyfingers** [comment]
@punkouter You can write it all in Azure App Services if that makes things easier. I used the Javascript (Node) backend (but if you are using C# is might be easier using VS as you mention). Add a new API using **Easy API** and name it '**hello**'. Then select the API and **Edit Script** to make live changes - 
<img width="583" alt="editscript" src="https://cloud.githubusercontent.com/assets/1880480/14618537/ee648b2a-05aa-11e6-89d5-04500c1aaea8.png">
<img width="697" alt="hello js" src="https://cloud.githubusercontent.com/assets/1880480/14618539/f320df38-05aa-11e6-87d4-66f336617a34.png">

Copy of demo 'hello' script

``` javascript
module.exports = {
    "get": function (req, res, next) {
        res.send(200, { message : 'Hello App :)' });
    }
}
```

**Comment by punkouter2021** [comment]
I am used to c# and API App so maybe that what confuses me. What I would like is to have everything in a VS project I can run locally and then Publish is Azure as needed..

I think they are converging API APP/MOBILE APP/WEB APP.. since they are all pretty much the same ? 

Ill try the .js way for now and paste in what you did above

**Comment by deadlyfingers** [comment]
Yes Mobile Services can be migrated to an Azure App Service now. Both give you a backend but App Service is newer and has a lot more things to play with! Yeah I should prob do a separate tutorial guide for JS and C# backends so people can use what they prefer to code in. But I presume most Unity coders would prefer C#...

**Comment by punkouter2021** [comment]
It feels strange coding in the cloud and not having everything local ... Since eventually Id want to write unit tests to test out the APIs Unity will call.. And testing in VS is a lot quicker than doing it in Unity I think

**Comment by deadlyfingers** [comment]
Will be closing this issue as I have added developer guide link on creating a Highscore table using Easy Tables. http://www.deadlyfingers.net/azure/azure-app-services-for-unity3d/

Please reopen if still an issue.
