### ISSUE TITLE
Various Errors/Warning But it seems to work./

### ISSUE THREAD

**Issue by punkouter2021** [Unity3dAzure/AppServicesDemo#18]
Should any of these Errors/Warning concern me ? 

![image](https://cloud.githubusercontent.com/assets/2973092/14572729/5f8cbeb0-031e-11e6-84b9-b3ea34176b3a.png)

**Comment by deadlyfingers** [comment]
The demo UI needs an update. When you delete the text from the Highscore input it freaks out as it can't convert an empty string into a Int. I'm going to overhaul the UI and use the new Unity UI as the legacy stuff is a bit old hat even for a demo. I've put this as issue #3
https://unity3d.com/learn/tutorials/topics/user-interface-ui

**Comment by deadlyfingers** [comment]
Closing this issue as this should be resolved with the new Unity UI update #3.
