### ISSUE TITLE
Request: Support and example code for using Azure Blob storage

### ISSUE THREAD

**Issue by Agrimat** [Unity3dAzure/AppServicesDemo#23]
These tools are great for working with databases on Azure from Unity. I went from having no idea where to start to doing database lookup very quickly.

I would love to be able to save and load files to Azure blob storage with the same convenience. An example of how to use the REST API to do that would be very helpful.

**Comment by deadlyfingers** [comment]
@Agrimat I aim to spin this out as a separate project. This project will only demo Azure App Services.

**Comment by deadlyfingers** [comment]
This new project will be added to the https://github.com/Unity3dAzure collection so I will be closing this issue.
