### ISSUE TITLE
Problem with UWP in Unity 5.5.1f

### ISSUE THREAD

**Issue by leonardomarquesdev** [Unity3dAzure/AppServicesDemo#39]
Table operations usually work in the editor. But not on my Windows Phone 10. Error occurs while trying to insert.

Should this plugin work on Windows Universal 10?

**Comment by A-Kojic** [comment]
Hi I just built this project on my WP 10 Nokia Lumia 1520 and all the operations are working fine so far (insert, update, delete).  I'm using Unity 5.5.0f. 

What is the exact error you are getting?

**Comment by leonardomarquesdev** [comment]
Good to know this, it means that the problem is with me, but come on:
I basically put an email form for the player to log in the game.
At the beginning of the game I call:

`_client = new MobileServiceClient (_appUrl);`
`_table = _client.GetTable <MecaUser> ("User");`

Then I try to insert the typed email into this User table in Azure Easy Tables
`StartCoroutine (_table.Insert <MecaUser> (user, OnInsertCompleted));`

And then I get the following error:

Insert Request: url
Response error status: 0 code: 0 error: Response failed status: 0 request url

**Comment by A-Kojic** [comment]
Hmm, not sure what might be the problem but have you tried the basic demo to run, just to validate that basic examples are working and then you can extend them with your stuff?

What phone are you using?

**Comment by leonardomarquesdev** [comment]
I just tested the Highscore example in the editor, it worked.
I was testing on my Windows Phone 10 and the same problem occurred, the same outputs.
It is a Lumia 640XL (RM-1067)

**Comment by A-Kojic** [comment]
@deadlyfingers any suggestions? In the project UnityWebRequest are used so it should work across all WP devices. @leonardoamaral92 can you send me your build file so I can run it on my Nokia and see how it behaves there?

**Comment by A-Kojic** [comment]
Do you have an internet connection on your phone?

Response error status:0 code:0 error:Response failed with status: 0 request

This is what I get when I turn off wifi, the same like you posted.

**Comment by leonardomarquesdev** [comment]
I can not believe I forgot something so obvious ...

It was the internet that was turned off anyway ... it's because the phone is not mine and I did not realize that it was not with the wifi connected ...

Many thanks @A-Kojic  and sorry for this silly problem!

**Comment by A-Kojic** [comment]
No problem, thanks @deadlyfingers for this great plugin! :)

**Comment by leonardoamaral92** [comment]
Unfortunately I came back with another problem now ..
I want to save the email, gamelevel0 and a password for the player, I got it in the Editor, I got the basic example in my Windows Phone, but I can not with my project, the information is null:

`OnInsertItemCompleted: {"id": "7ae9bff2-be69-499b-8846-89f6a9bb538d", "createdAt": "2017-04-06T18: 44: 37.739Z", "updatedAt": "2017-04-06T18: 44: 37,739 Z ", "Version": "MQ ==", "deleted": false, "email": null, "gameLevel0": null, "password": null, "ROW_NUMBER": ""}`

Do you know what that might be? @A-Kojic
