### ISSUE TITLE
Missing Files

### ISSUE THREAD

**Issue by rossadamsm** [Unity3dAzure/AppServicesDemo#43]
When opening the project in Unity there seems to be several files missing. More specifically
DataModel, Azure, RESTClient, AppServiceClient, AppServiceTable, IRestResponse

**Comment by rossadamsm** [comment]
Sorry never mind. Didn't see the dependencies because I wasn't paying attention

**Comment by deadlyfingers** [comment]
Yes I thought it good to move the reusable parts into their own repos. I'm using git sub modules to handle this for now until a package manager is available in Unity.
