### ISSUE TITLE
New mobile app services require zumo 2.0 header

### ISSUE THREAD

**Issue by punkouter2021** [Unity3dAzure/AppServicesDemo#7]

**Comment by deadlyfingers** [comment]
I intend to migrate this project to use the new Azure App Service but want to continue to support Mobile Services. I have discussed the proposed changes here: 
https://github.com/Unity3dAzure/MobileServices/issues/1

**Comment by deadlyfingers** [comment]
Now we have 2 demos! - 

##Mobile Services Demo
![unity-mobileservicesdemo](https://cloud.githubusercontent.com/assets/1880480/14404803/c8287754-fe76-11e5-8b0c-7ba729a8c19d.png)

##New App Services Demo
![unity-azureappservicesdemo](https://cloud.githubusercontent.com/assets/1880480/14404802/c82512da-fe76-11e5-91ad-316fcd70fd5c.png)
