### ISSUE TITLE
Extend support for Azure Mobile Service identities

### ISSUE THREAD

**Issue by deadlyfingers** [Unity3dAzure/AppServicesDemo#9]
Mobile Service Demo uses Facebook token. Should also extend demo with Twitter, Google and Microsoft Account identities.

**Comment by deadlyfingers** [comment]
plus AAD
- https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-how-to-configure-active-directory-authentication

**Comment by deadlyfingers** [comment]
Demo works with Facebook and Twitter identities. Support for others identity providers are also available. 

https://github.com/Unity3dAzure/AppServicesDemo/pull/41

**Comment by ghost** [comment]
Could you please provide us with a detailed tutorial for just Azure Active Directory Authentication to unity project ?
